language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-tomsite' ]; then cd .. && eval "mv $currentfolder generator-tomsite" && cd generator-tomsite; fi

